# Site settings
baseURL = "https://xumijian.me"
languageCode = "en-US"
title = "Mijian Xu"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2020 Mijian Xu"

[params]

  # Metadata for search engines and social sharing
  author = "Mijian Xu"
  description = "Seismology"
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "images/favicon.jpg"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"
  
  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://blog.xumijian.me"
      
      [[params.links.list1.link]]
        text = "Academic Home"
        url = "https://home.xumijian.me"

      [[params.links.list1.link]]
        text = "Documents"
        url = "https://docs.xumijian.me"


  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Github"
        url = "https://github.com/xumi1993"

      [[params.links.list2.link]]
        text = "Gitlab"
        url = "https://git.nju.edu.cn/xumi1993"

      [[params.links.list2.link]]
        text = "Google Scholar"
        url = "https://scholar.google.com/citations?user=AGBUZWoAAAAJ&hl=zh-CN&oi=ao"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Links"

      [[params.links.list3.link]]
        text = "Seispy"
        url = "https://seispy.xumijian.me"

      [[params.links.list3.link]]
        text = "SplitRFlab"
        url = "https://github.com/xumi1993/SplitRFLab"


  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
